name: potability
description: A Smart Water Monitoring and Potability Prediction App
version: 1.0.0+1
environment:
  sdk: ^3.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.6
  lottie: ^3.3.1
  mqtt_client: ^10.0.0
  http: ^1.2.1
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  flutter_svg: ^2.0.10
  intl: ^0.20.2
  file_picker: ^10.2.0
  fl_chart: ^1.0.0
  url_launcher: ^6.1.7
dependency_overrides:
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  mime: ^2.0.0
  petitparser: ^7.0.0
  vector_math: ^2.2.0
  xml: ^6.6.0
  characters: ^1.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/ph.png
    - assets/temperature.png
    - assets/turbidity.png
    - assets/tds.png
    - assets/do.png
    - assets/block.png
    - assets/clear.png
    - assets/danger.png
    - assets/error.png
    - assets/filter.png
    - assets/leaf.png
    - assets/ph.svg
    - assets/temperature.svg
    - assets/turbidity.svg
    - assets/tds.svg
    - assets/do.svg
    - assets/block.svg
    - assets/clear.svg
    - assets/danger.svg
    - assets/error.svg
    - assets/filter.svg
    - assets/leaf.svg
    - assets/water.json
    - assets/water_full.json
    - assets/menu.json
    - assets/uni_logo.png
    - assets/uni_logo_full.png
    - assets/water_drop.png
    - assets/aws/cert.pem
    - assets/aws/private.key
    - assets/aws/CA.pem
  fonts:
    - family: SairaExpanded
      fonts:
        - asset: assets/fonts/Saira_Expanded-Medium.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/main_logo_circle.png
  min_sdk_android: 21 
  remove_alpha_ios: true
  android_adaptive_icon_foreground: assets/water_drop.png 
  android_adaptive_icon_background: "#00BCD4"
  web:
    generate: true
    image_path: assets/main_logo_circle.png
    background_color: "#FFFFFF" 
    theme_color: "#00BCD4" 
  windows:
    generate: true
    image_path: assets/main_logo_circle.png
    icon_size: 48 
  macos:
    generate: true
    image_path: assets/main_logo_circle.png