name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master', depending on your default branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4' # Use your Flutter version, e.g., '3.22.x' or 'stable'
          channel: 'stable' # Ensure this matches your Flutter channel

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Enable Web
        run: flutter config --enable-web

      - name: Build Web App
        run: flutter build web --release --base-href="/Potability/" # IMPORTANT: Replace 'aquasense' with your repo name

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Use the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # If your repo is a User/Organization Page (your-username.github.io),
          # you would publish to the 'main' or 'master' branch directly.
          # For a Project Page (your-username.github.io/repo-name/),
          # it's typical to publish to 'gh-pages' branch.
          publish_branch: gh-pages